In [2]:
import numpy as np
import pandas as pd

##creating a dataframe

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 56, 37],
    'Salary': [65000, 70000, 62000, 85000],
    'City': ['kol', 'del', 'che', 'ban'],
}
pd.DataFrame(data)

    Name  Age  Salary City
0   John   28   65000  kol
1   Anna   34   70000  del
2  Peter   56   62000  che
3  Linda   37   85000  ban

In [4]:
data_list = [
    ['jogn', 28, 'del', 65000],
    ['anna', 34, 'kol', 70000],
    ['peter', 29, 'che', 85000],
    ['linda', 45, 'ban', 62000]
]
df2 = pd.DataFrame(data_list)
columns = ["name", "age", "city", "salary"]
df2 = pd.DataFrame(data_list, columns= columns)
df2

    name  age city  salary
0   jogn   28  del   65000
1   anna   34  kol   70000
2  peter   29  che   85000
3  linda   45  ban   62000

In [10]:
df2[['name', 'city']]

    name city
0   jogn  del
1   anna  kol
2  peter  che
3  linda  ban

In [ ]:
df2["designation"]