In [1]:
import pandas as pd
import numpy as np

In [2]:
d1 = {'Social_media_followers':[1000000, np.nan, 2000000, 1310000, 1700000, np.nan, 4100000, 1600000, 2200000, 1000000],
'Sold_out':[1,0,0,1,0,0,0,1,0,1]}

In [3]:
df1 = pd.DataFrame(data = d1)

In [4]:
df1

   Social_media_followers  Sold_out
0               1000000.0         1
1                     NaN         0
2               2000000.0         0
3               1310000.0         1
4               1700000.0         0
5                     NaN         0
6               4100000.0         0
7               1600000.0         1
8               2200000.0         0
9               1000000.0         1

In [5]:
X1 = df1[['Social_media_followers']]

In [6]:
y1 = df1[['Sold_out']]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3, random_state=19)

In [9]:
X1_train.shape

(7, 1)

In [10]:
X1_test.shape

(3, 1)

In [11]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(strategy='mean') #fills in mssing values(NaN) with mean of that column, works col by col

In [13]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression() #classification algo used to predict categpries, works well for binary classification, fits sigmoid curve to the data

In [15]:
from sklearn.pipeline import make_pipeline

In [ ]:
pipe1 = make_pipeline(imputer, lr) #chains multiple processing steps together into one object, impputer fills in mikssing values and lr trains logistic reg model on the imputed data

In [17]:
pipe1.fit(X1_train, y1_train )

c:\Users\KIIT0001\OneDrive\Desktop\mllearnings\scikitlearn\.venv\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('logisticregression', LogisticRegression())])

In [19]:
pipe1.score(X1_train, y1_train)

1.0

In [21]:
pipe1.score(X1_test, y1_test)

0.6666666666666666

In [22]:
pipe1.named_steps.simpleimputer.statistics_

array([2051666.66666667])

In [23]:
pipe1.named_steps.logisticregression.coef_

array([[-9.72872687e-05]])

advanced pipeline

In [24]:
d2 = {'Genre':['Rock', 'Metal', 'Bluegrass', 'Rock', np.nan, 'Rock', 'Rock', np.nan, 'Bluegrass', 'Rock'],
'Social_media_followers':[1000000, np.nan, 2000000, 1310000, 1700000, np.nan, 4100000, 1600000, 2200000, 1000000],
'Sold_out':[1,0,0,1,0,0,0,1,0,1]}

In [25]:
df = pd.DataFrame(data = d2)

In [26]:
df

       Genre  Social_media_followers  Sold_out
0       Rock               1000000.0         1
1      Metal                     NaN         0
2  Bluegrass               2000000.0         0
3       Rock               1310000.0         1
4        NaN               1700000.0         0
5       Rock                     NaN         0
6       Rock               4100000.0         0
7        NaN               1600000.0         1
8  Bluegrass               2200000.0         0
9       Rock               1000000.0         1

In [27]:
X = df.iloc[:, 0:2]

In [28]:
y = df.iloc[:, 2]

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=70)

In [31]:
num_cols = ['Social_media_followers']

In [32]:
cat_cols = ['Genre']

In [33]:
from sklearn.pipeline import Pipeline

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
num_pipeline = Pipeline(
    steps = [
        ('impute', SimpleImputer(strategy='mean')),
        ('scale', StandardScaler())
    ]
)

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
cat_pipeline = Pipeline(steps = [
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('one-hot-encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [38]:
from sklearn.compose import ColumnTransformer

In [40]:
col_transformer = ColumnTransformer(transformers = [
    ('num_pipeline', num_pipeline, num_cols),
    ('cat_pipeline', cat_pipeline, cat_cols),
],
    remainder = 'drop',
    n_jobs= -1
)

In [41]:
from sklearn.tree import DecisionTreeClassifier

In [42]:
dtc = DecisionTreeClassifier()

In [43]:
pipefinal = make_pipeline(col_transformer, dtc)

In [44]:
pipefinal.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(n_jobs=-1,
                                   transformers=[('num_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['Social_media_followers']),
                                                 ('cat_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('one-hot-encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Genre'])])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [45]:
pipefinal.score(X_test, y_test)

1.0

saving pipeline

In [46]:
import joblib

In [47]:
joblib.dump(pipefinal, "pipe.joblib")

['pipe.joblib']

In [48]:
pipefinal2 = joblib.load("pipe.joblib")