In [2]:
import numpy as np
import pandas as pd

##creating a dataframe

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 56, 37],
    'Salary': [65000, 70000, 62000, 85000],
    'City': ['kol', 'del', 'che', 'ban'],
}
pd.DataFrame(data)

    Name  Age  Salary City
0   John   28   65000  kol
1   Anna   34   70000  del
2  Peter   56   62000  che
3  Linda   37   85000  ban

In [4]:
data_list = [
    ['jogn', 28, 'del', 65000],
    ['anna', 34, 'kol', 70000],
    ['peter', 29, 'che', 85000],
    ['linda', 45, 'ban', 62000]
]
df2 = pd.DataFrame(data_list)
columns = ["name", "age", "city", "salary"]
df2 = pd.DataFrame(data_list, columns= columns)
df2

    name  age city  salary
0   jogn   28  del   65000
1   anna   34  kol   70000
2  peter   29  che   85000
3  linda   45  ban   62000

In [5]:
df2[['name', 'city']]

    name city
0   jogn  del
1   anna  kol
2  peter  che
3  linda  ban

In [6]:
df2["designation"] = ['doctor', 'eng', 'texaher', 'painter']
df2

    name  age city  salary designation
0   jogn   28  del   65000      doctor
1   anna   34  kol   70000         eng
2  peter   29  che   85000     texaher
3  linda   45  ban   62000     painter

removing col

In [7]:
df2.drop(0, axis=0)

    name  age city  salary designation
1   anna   34  kol   70000         eng
2  peter   29  che   85000     texaher
3  linda   45  ban   62000     painter

selecting rows

In [8]:
df2.loc[[0,1]]

   name  age city  salary designation
0  jogn   28  del   65000      doctor
1  anna   34  kol   70000         eng

In [ ]:
df2.iloc[3]

name             linda
age                 45
city               ban
salary           62000
designation    painter
Name: 3, dtype: object

In [12]:
df2.loc[[0,1], ['city', 'salary']]

  city  salary
0  del   65000
1  kol   70000

In [13]:
df2[df2["age"]>30]

    name  age city  salary designation
1   anna   34  kol   70000         eng
3  linda   45  ban   62000     painter

In [15]:
df2[(df2['age'] > 30) & (df2['city'] == 'kol')]

   name  age city  salary designation
1  anna   34  kol   70000         eng