In [3]:
import numpy as np
import pandas as pd

merging 2 dataframes

In [10]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['John','Anna','peter','linda','bob'],
    'department': ['hr','it','finance','it','hr']
})
employees
salaries = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'salary': [60000,70000,80000,65000,90000],
    'bonus': [6000,12000,5000,7000,8000]
})
salaries

   employee_id  salary  bonus
0            1   60000   6000
1            2   70000  12000
2            3   80000   5000
3            6   65000   7000
4            7   90000   8000

In [11]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         hr   60000   6000
1            2   Anna         it   70000  12000
2            3  peter    finance   80000   5000

In [12]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         hr  60000.0   6000.0
1            2   Anna         it  70000.0  12000.0
2            3  peter    finance  80000.0   5000.0
3            4  linda         it      NaN      NaN
4            5    bob         hr      NaN      NaN
5            6    NaN        NaN  65000.0   7000.0
6            7    NaN        NaN  90000.0   8000.0

In [13]:
pd.merge(employees,salaries,on='employee_id',how='left')
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         hr   60000   6000
1            2   Anna         it   70000  12000
2            3  peter    finance   80000   5000
3            6    NaN        NaN   65000   7000
4            7    NaN        NaN   90000   8000

concatenation of 2 dataframes

In [15]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})
df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})
pd.concat([df1,df2])
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

joing 2 ddataframes

In [17]:
df1 = pd.DataFrame({
    'name': ['alice','bob','charlie']
}, index=[1,2,3])

df2 = pd.DataFrame({
    'score': [85,90,75]
}, index=[2,3,4])
df1.join(df2, how='outer')

      name  score
1    alice    NaN
2      bob   85.0
3  charlie   90.0
4      NaN   75.0